version: '3'

services:
  spark-master:
    image: apache/spark:v3.3.2
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    hostname: spark-master
    environment:
      - SPARK_CONF_DIR=/conf
      - SPARK_PUBLIC_DNS=localhost
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 8080:8080

  spark-worker:
    image: apache/spark:v3.3.2
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    hostname: spark-worker
    environment:
      - SPARK_CONF_DIR=/conf
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - SPARK_PUBLIC_DNS=localhost
    links:
      - spark-master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 7077
      - 6066
    ports:
      - 8081:8081

